### ISSUE TITLE
安装引导的时候出现禁止符号。

### ISSUE THREAD

**Issue by micenote** [Huang-JunDong/efi#1]
安装引导的时候出现禁止符号。

**Comment by Huang-JunDong** [comment]
截图给我看下

**Comment by Huang-JunDong** [comment]
> 安装引导的时候出现禁止符号。

你看配置是否和我一致，然后主板bios是否按照黑果调整了某些选项

**Comment by micenote** [comment]
ROG B460-i 主板，i5-10600KCPU ，没有独显。没有免驱网卡。

**Comment by Huang-JunDong** [comment]
> ROG B460-i 主板，i5-10600KCPU ，没有独显。没有免驱网卡。

那这个config 需要调整下 因为这个config目前是针对独显机型

**Comment by micenote** [comment]
> > ROG B460-i 主板，i5-10600KCPU ，没有独显。没有免驱网卡。
> 
> 那这个config 需要调整下 因为这个config目前是针对独显机型

好的，谢谢，我自己重新做了一个，目前正常了。
